spring:
  config:
    import: optional:file:../../.env[.properties]

  application:
    name: stock-analyzer

  profiles:
    active: ${SPRING_PROFILE:dev}


  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cache:
    type: simple

server:
  port: 8080

ml:
  service:
    url: ${ML_SERVICE_URL:http://localhost:8000}

moex:
  api:
    url: https://iss.moex.com/iss

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

logging:
  level:
    ru.vkr: INFO
    org.springframework.web: WARN